<?php

namespace Database\Seeders;

use App\Models\AllTasks;
use App\Models\Project;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::create([
            'name' => 'ANGELO ESTRADA ANDRES',
            'user_type' => 'college_head',
            'email' => 'angeloandres521@yahoo.com',
            'password' => bcrypt('Cosmiku521*'),
            'email_verified_at' => now()
        ]);

        User::create([
            'name' => 'Sample Student',
            'user_type' => 'student',
            'email' => 'angeloandres521@gmail.com',
            'password' => bcrypt('Cosmiku521*'),
            'email_verified_at' => now()
        ]);

        $tasks = [
            [
                'name' => 'Introduction to Computing',
                'course_code' => 'CC113-m',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Computer Programming 1, Lecture',
                'course_code' => 'CC132-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 2,
            ],
            [
                'name' => 'Computer Programming 1, Laboratory',
                'course_code' => 'CC131L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => 2,
                'units' => 1,
            ],
            [
                'name' => 'Understanding the Self',
                'course_code' => 'GEC1-M',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'The Contemporary World',
                'course_code' => 'GEC3-M',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Science, Technology, and Society',
                'course_code' => 'GEC7-M',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Fundamentals of Math Analysis',
                'course_code' => 'MATHA05S-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 5,
            ],
            [
                'name' => 'National Service Training Program 1',
                'course_code' => 'NSTP1-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Physical Fitness',
                'course_code' => 'PE1-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 2,
            ],
        // First year 2nd Sem (ID 10)
        [
            'name' => 'Computer Programming 2, Lecture',
            'course_code' => 'CC102-M',
            'task_type' => 'special',
            'gec_type' => null,
            'prerequisite_id' => 3,
            'corequisite_id' => 10,
            'units' => 2,
        ],
        [
            'name' => 'Computer Programming 2, Laboratory',
            'course_code' => 'CC101L-M',
            'task_type' => 'special',
            'gec_type' => null,
            'prerequisite_id' => 2,
            'corequisite_id' => 11,
            'units' => 1,
        ],
            [
                'name' => 'Discrete Structures',
                'course_code' => 'CS103',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Linear Algebra',
                'course_code' => 'CS123-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Mathematics in the Modern World',
                'course_code' => 'GEC4-M',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Purposive Communication',
                'course_code' => 'GEC5-M',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Art Appreciation',
                'course_code' => 'GEC6-M',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Differential and Integral Calculus',
                'course_code' => 'MATHA35-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => 7,
                'corequisite_id' => null,
                'units' => 5,
            ],
            [
                'name' => 'National Service Training Program 2',
                'course_code' => 'NSTP2-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => 8,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Rhythmic Activities',
                'course_code' => 'PE2-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => 9,
                'corequisite_id' => null,
                'units' => 2,
            ],
            [
                'name' => 'Data Structures and Algorithms, Lecture',
                'course_code' => 'CC212-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 11,
                'corequisite_id' => 20,
                'units' => 2,
            ],
            [
                'name' => 'Data Structures and Algorithms, Laboratory',
                'course_code' => 'CC211L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 10,
                'corequisite_id' => 21,
                'units' => 1,
            ],
            [
                'name' => 'Human Computer Interaction',
                'course_code' => 'CC233-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 10,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Object Oriented Programming, Lecture',
                'course_code' => 'CC252-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 11,
                'corequisite_id' => null,
                'units' => 2,
            ],
            [
                'name' => 'Object Oriented Programming, Laboratory',
                'course_code' => 'CC251L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 10,
                'corequisite_id' => null,
                'units' => 1,
            ],
            [
                'name' => 'Computer Architecture and Organization, Laboratory',
                'course_code' => 'CC271L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 10,
                'corequisite_id' => null,
                'units' => 1,
            ],
            [
                'name' => 'Computer Architecture and Organization, Lecture',
                'course_code' => 'CC272-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 11,
                'corequisite_id' => 26,
                'units' => 2,
            ],
            [
                'name' => 'Combinatronics and Graph Theory',
                'course_code' => 'CS213-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 12,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Readings in Philippine History',
                'course_code' => 'GEC2',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Ethics',
                'course_code' => 'GEC8-M',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Individual and Dual Sports',
                'course_code' => 'PE3-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => 19,
                'corequisite_id' => null,
                'units' => 2,
            ],
        // 2yr 2sem (ID 32)
            [
                'name' => 'Information Management, Laboratory',
                'course_code' => 'CC201L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 20,
                'corequisite_id' => null,
                'units' => 1,
            ],
            [
                'name' => 'Information Management, Lecture',
                'course_code' => 'CC202-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 21,
                'corequisite_id' => 32,
                'units' => 2,
            ],
            [
                'name' => 'Application Development and Emerging Technologies',
                'course_code' => 'CC223-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 23,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Design and Analysis of Algorithms',
                'course_code' => 'CS203-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 20,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Networks and Communications, Laboratory',
                'course_code' => 'CS221L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 26,
                'corequisite_id' => null,
                'units' => 1,
            ],
            [
                'name' => 'Networks and Communications, Lecture',
                'course_code' => 'CS222-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 27,
                'corequisite_id' => 35,
                'units' => 2,
            ],
            [
                'name' => 'Operating Systems, Laboratory',
                'course_code' => 'CS241L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 23,
                'corequisite_id' => null,
                'units' => 1,
            ],
            [
                'name' => 'Operating Systems, Lecture',
                'course_code' => 'CS242-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 24,
                'corequisite_id' => 37,
                'units' => 2,
            ],
            [
                'name' => 'CS Professional Elective 1',
                'course_code' => 'CSE1-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Probability and Statistics',
                'course_code' => 'MATHSTAT03-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Team Sports',
                'course_code' => 'PE4-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => 9,
                'corequisite_id' => null,
                'units' => 2,
            ],
        // 3yr 1sem (ID 42)
        [
            'name' => 'Web Development, Lecture',
                'course_code' => 'CC312-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 33,
                'corequisite_id' => 42,
                'units' => 2,
            ],
            [
                'name' => 'Web Development, Laboratory',
                'course_code' => 'CC311L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 32,
                'corequisite_id' => 43,
                'units' => 1,
            ],
            [ // ALERT KASE 4 TALAGA DAPAT REQUSITE NYA [CS222-M, CS221L-M CC202-M, CC201L-M]
                'name' => 'Information Assurance and Security',
                'course_code' => 'CS313-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 35,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [ // prereq 4 [CC252-M, CC251L-M, CC202-M, CC201L-M] chose 202(id 33) from 2yr2sem ; pede ren CC252(id 25) para unique which is 2yr1sem
                'name' => 'Software Engineering 1, Lecture',
                'course_code' => 'CS332-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 33,
                'corequisite_id' => 45,
                'units' => 2,
            ],
            [
                'name' => 'Software Engineering 1, Laboratory',
                'course_code' => 'CS331L-M ',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 32,
                'corequisite_id' => 46,
                'units' => 1,
            ],
            [
                'name' => 'Automata Theory and Formal Languages',
                'course_code' => 'CS353-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 35,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [ // [CC202-M, CC201L-M, MATHSTAT03-M] 34, 33 ,40
                'name' => 'Data Analytics',
                'course_code' => 'CS373-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 40,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [ // [CC242-M, CC241L-M]  38, 37
                'name' => 'Parallel and Distributed Computing',
                'course_code' => 'CS393-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 37,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'CS Professional Elective 2',
                'course_code' => 'CSE2-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
        // 3yr 2sem (ID 51)
            [
                'name' => 'Methods of Research in Computing',
                'course_code' => 'CC303-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Artificial Intelligence, Lecture',
                'course_code' => 'CS322-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 48,
                'corequisite_id' => 52,
                'units' => 2,
            ],
            [
                'name' => 'Artificial Intelligence, Laboratory ',
                'course_code' => 'CS321L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 48,
                'corequisite_id' => 53,
                'units' => 1,
            ],
            [
                'name' => 'Software Engineering 2, Lecture',
                'course_code' => 'CS342-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 46,
                'corequisite_id' => 54,
                'units' => 2,
            ],
            [
                'name' => 'Software Engineering 2, Laboratory',
                'course_code' => 'CS341L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 45,
                'corequisite_id' => 55,
                'units' => 1,
            ],
            [
                'name' => 'Programming Language (Design and Implementation), Laboratory',
                'course_code' => 'CS361L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 47,
                'corequisite_id' => null,
                'units' => 1,
            ],
            [
                'name' => 'Programming Language (Design and Implementation), Lecture',
                'course_code' => 'CS362-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 47,
                'corequisite_id' => null,
                'units' => 2,
            ],
            [
                'name' => 'Modeling and Simulation',
                'course_code' => 'CS383-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 48,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'CS Professional Elective 3',
                'course_code' => 'CSE3-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'CS Professional Elective 4',
                'course_code' => 'CSE4-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
        // 4yr 1sem (ID 61)
            [
                'name' => 'Social and Professional Issues',
                'course_code' => 'CC413-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Thesis Writing 1',
                'course_code' => 'CS413-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Living in the IT Era',
                'course_code' => 'GEE11D-M',
                'task_type' => 'gec',
                'gec_type' => 'gee',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'The Entrepreneurial Mind',
                'course_code' => 'GEE12D-M',
                'task_type' => 'gec',
                'gec_type' => 'gee',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Reading Visual Art',
                'course_code' => 'GEE13D-M',
                'task_type' => 'gec',
                'gec_type' => 'gee',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Life and Works of Rizal',
                'course_code' => 'GEM14-M',
                'task_type' => 'special',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
        // 4yr 2sem (ID 67)
            [
                'name' => 'Supervised Industrial Training (486 hours)',
                'course_code' => 'CS406-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 9,
            ],
            [
                'name' => 'Thesis Writing 2',
                'course_code' => 'CS423',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 61,
                'corequisite_id' => null,
                'units' => 3,
            ],
        // from cs NS (ID 69)
        [
            'name' => 'General Chemistry, Lecture',
                'course_code' => 'CHEMGEN-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 1,
            ],
            [
                'name' => 'General Chemistry, Laboratory',
                'course_code' => 'CHEMGENL-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 4,
            ],
            [
                'name' => 'PRECALCULUS',
                'course_code' => 'MATHA05-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 5,
            ],
            // 1-2 (ID 72)
            [
                'name' => 'General Physics, Lecture',
                'course_code' => 'PHYSGEN-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 4,
            ],
            [
                'name' => 'General Physics, Laboratory',
                'course_code' => 'PHYSGENL-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 1,
            ],
            // 2-1 (ID 74)
            [
                'name' => 'Readings in Philippine History',
                'course_code' => 'GEC2-M',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            // 3-1 (ID 75)
            [
                'name' => 'Web Development, Lecture',
                'course_code' => 'CC312',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 33,
                'corequisite_id' => 75,
                'units' => 2,
            ],
            [
                'name' => 'Web Development, Laboratory',
                'course_code' => 'CC331L',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 32,
                'corequisite_id' => 76,
                'units' => 1,
            ],
            [
                'name' => 'Information Assurance and Security',
                'course_code' => 'CS313',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 32,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Software Engineering 1, Lecture',
                'course_code' => 'CS332',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 33,
                'corequisite_id' => 78,
                'units' => 2,
            ],
            [
                'name' => 'Software Engineering 1, Laboratory',
                'course_code' => 'CS331L',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 32,
                'corequisite_id' => 79,
                'units' => 1,
            ],
            [
                'name' => 'Languages',
                'course_code' => 'CS353',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 35,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Data Analytics',
                'course_code' => 'CS373',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 40,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'CS Professional Elective 2',
                'course_code' => 'CSE2',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'The Contemporary World',
                'course_code' => 'GEC3',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Purposive Communication',
                'course_code' => 'GEC5',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Parallel and Distributed Computing',
                'course_code' => 'CS393',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 37,
                'corequisite_id' => null,
                'units' => 3,
            ],
            // ID 85 above           
        // BSIS 1-1 (ID 86)
            [
                'name' => 'CWTS1/ROTC1',
                'course_code' => 'NSTP1-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            // 1-2 (ID 87)
            [
                'name' => 'Fundamentals of Information Systems',
                'course_code' => 'IS103-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 1,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Probability and Statistics',
                'course_code' => 'MATHC03-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'CWTS2/ROTC2',
                'course_code' => 'NSTP2-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => 8,
                'corequisite_id' => null,
                'units' => 3,
            ],
            // 2-1 (ID 90)
            [
                'name' => 'Organization and Management Concepts',
                'course_code' => 'IS213-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'IS Professional Elective 1',
                'course_code' => 'ISE1',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Ethics',
                'course_code' => 'GEC8',
                'task_type' => 'gec',
                'gec_type' => 'gec',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Individual and Dual Sports',
                'course_code' => 'PE3',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => 9,
                'corequisite_id' => null,
                'units' => 2,
            ],
            // 2-2 (ID 94)
            [
                'name' => 'Accounting and Financial Management',
                'course_code' => 'IS203-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 90,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Business Process Management',
                'course_code' => 'IS223-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 90,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'IT Infrastructure and Network Technologies',
                'course_code' => 'IS243-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Quantitative Methods',
                'course_code' => 'IS263-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 88,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'IS Professional Elective 2',
                'course_code' => 'ISE2-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            // 3-1 (ID 99)
            [
                'name' => 'Systems Analysis and Design',
                'course_code' => 'IS313-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 95,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Financial Management Information Systems',
                'course_code' => 'IS333-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 94,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'IS Project Management 1',
                'course_code' => 'IS353-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 95,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Evaluation of Business Performance',
                'course_code' => 'IS373',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 95,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Information Assurance and Security 1',
                'course_code' => 'IS393-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 96,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'IS Professional Elective 3',
                'course_code' => 'ISE3-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            // 3-2 (ID 105)
            [
                'name' => 'Business Intelligence',
                'course_code' => 'CC323',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Information Assurance and Security 2',
                'course_code' => 'IS303-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 103,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Enterprise Architecture',
                'course_code' => 'IS323-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 99,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'IS Strategy, Management, and Acquisition',
                'course_code' => 'IS343--M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 101,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'IS Project Management 2',
                'course_code' => 'IS363--M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 101,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'IS Professional Elective 4',
                'course_code' => 'ISE4-M',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],            
            // 4-1 ID 111
            [
                'name' => 'IS Capstone Project 1',
                'course_code' => 'IS413-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            // 4-2 ID 112
            [
                'name' => 'IS Capstone Project 2',
                'course_code' => 'IS423-M',
                'task_type' => 'special',
                'gec_type' => 'elective',
                'prerequisite_id' => 111,
                'corequisite_id' => null,
                'units' => 3,
            ],
        // BSIT 1-2 ID 113
            [
                'name' => 'Discrete Structures',
                'course_code' => 'IT103-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Human Computer Interaction',
                'course_code' => 'IT123-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            // 2-1 ID 115
            [
                'name' => 'Platform Technologies, Lecture',
                'course_code' => 'IT212--M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 11,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Platform Technologies, Laboratory',
                'course_code' => 'IT211L--M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 10,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'IT Professional Elective 1',
                'course_code' => '',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            // 2-2 ID 118
            [
                'name' => 'Quantitative Methods (Inc.  Modeling & Simulation)',
                'course_code' => 'IT203-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 23,
                'corequisite_id' => 33,
                'units' => 3,
            ],
            [
                'name' => 'Computer Networking 1, Lecture',
                'course_code' => 'IT222--M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 116,
                'corequisite_id' => 119,
                'units' => 1,
            ],
            [
                'name' => 'Computer Networking 1, Laboratory',
                'course_code' => 'IT221L',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 115,
                'corequisite_id' => 120,
                'units' => 2,
            ],
            [
                'name' => 'Multimedia Authoring & Production, Lecture',
                'course_code' => 'IT242-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 24,
                'corequisite_id' => 121,
                'units' => 2,
            ],
            [
                'name' => 'Multimedia Authoring & Production, Laboratory',
                'course_code' => 'IT241L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 23,
                'corequisite_id' => 122,
                'units' => 1,
            ],
            [
                'name' => 'Programming Laguage (Design and Implementation), Lecture',
                'course_code' => 'IT262--M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 27,
                'corequisite_id' => 123,
                'units' => 2,
            ],
            [
                'name' => 'Programming Laguage (Design and Implementation), Laboratory',
                'course_code' => 'IT261L--M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 26,
                'corequisite_id' => 124,
                'units' => 1,
            ],
            [
                'name' => 'IT Professional Elective 2',
                'course_code' => 'ITE2-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],            
            // 3-1 ID 126
            [
                'name' => 'Computer Networking 2, Lecture',
                'course_code' => 'IT312--M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 120,
                'corequisite_id' => 126,
                'units' => 2,
            ],
            [
                'name' => 'Computer Networking 2, Laboratory',
                'course_code' => 'IT311L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 119,
                'corequisite_id' => 127,
                'units' => 1,
            ],
            [
                'name' => 'Systems Integration and Architecture 1, Lecture',
                'course_code' => 'IT332LEC-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => 128,
                'units' => 2,
            ],
            [
                'name' => 'Systems Integration and Architecture 1, Laboratory',
                'course_code' => 'IT331LAB-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => 129,
                'units' => 1,
            ],
            [
                'name' => 'Advanced Database Systems, Lecture',
                'course_code' => 'IT352-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 33,
                'corequisite_id' => 130,
                'units' => 2,
            ],
            [
                'name' => 'Advanced Database Systems, Laboratory',
                'course_code' => 'IT351L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 32,
                'corequisite_id' => 131,
                'units' => 1,
            ],
            [
                'name' => 'Microcontroller Systems, Lecture',
                'course_code' => 'IT371LEC-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 27,
                'corequisite_id' => 132,
                'units' => 2,
            ],
            [
                'name' => 'Microcontroller Systems, Laboratory',
                'course_code' => 'IT371LAB-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 26,
                'corequisite_id' => 133,
                'units' => 1,
            ],
            [
                'name' => 'IT Professional Elective  3',
                'course_code' => 'ITE3',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            // 3-2 ID 135
            [
                'name' => 'Information Assurance and Security 1, Lecture',
                'course_code' => 'IT302-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 127,
                'corequisite_id' => 135,
                'units' => 2,
            ],
            [
                'name' => 'Information Assurance and Security 1, Laboratory',
                'course_code' => 'IT301L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 126,
                'corequisite_id' => 136,
                'units' => 1,
            ],
            [
                'name' => 'Systems Integration and Architecture 2, Lecture',
                'course_code' => 'IT342-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 129,
                'corequisite_id' => 137,
                'units' => 2,
            ],
            [
                'name' => 'Systems Integration and Architecture 2, Laboratory',
                'course_code' => 'IT341L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 128,
                'corequisite_id' => 138,
                'units' => 1,
            ],
            [
                'name' => 'IT Professional Elective  4',
                'course_code' => 'ITE4',
                'task_type' => 'gec',
                'gec_type' => 'elective',
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],            
            // 4-1 ID 140
            [
                'name' => 'IT Capstone & Research 1',
                'course_code' => 'IT413-M',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Systems Administration and Maintenance',
                'course_code' => 'IT433',
                'task_type' => 'standing',
                'gec_type' => null,
                'prerequisite_id' => null,
                'corequisite_id' => null,
                'units' => 3,
            ],
            [
                'name' => 'Information Assurance and Security 2, Lecture',
                'course_code' => 'IT452-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 136,
                'corequisite_id' => 142,
                'units' => 2,
            ],
            [
                'name' => 'Information Assurance and Security 2, Laboratory',
                'course_code' => 'IT451L-M',
                'task_type' => 'special',
                'gec_type' => null,
                'prerequisite_id' => 135,
                'corequisite_id' => 143,
                'units' => 1,
            ],
            // 4-2 ID 144
            [
                'name' => 'IT Capstone & Research 2',
                'course_code' => 'IT423--M',
                'task_type' => 'special',
                'gec_type' => 'elective',
                'prerequisite_id' => 140,
                'corequisite_id' => null,
                'units' => 3,
            ],
        ];

        foreach ($tasks as $task) {
            AllTasks::create($task);
        }
    }
}
